Update .zappr.yaml
prayerslayer/invalid-zappr-config-test pull request #16
Opened 2016-09-04 19:00 UTC by prayerslayer

2016-09-23 16:53 UTC, prayerslayer commented
Oh im sorry

2016-09-23 17:05 UTC, prayerslayer commented
what is going on here

2016-10-25 12:30 UTC, prayerslayer commented
👍

2016-10-25 12:50 UTC, prayerslayer commented
👍

2016-10-25 14:35 UTC, prayerslayer commented
:-1:

2016-10-25 14:36 UTC, prayerslayer commented
this comment is unrelated

2016-10-27 13:02 UTC, prayerslayer commented
👍

2016-10-27 13:29 UTC, prayerslayer commented
👍

2016-11-11 10:18 UTC, zappr-test submitted a review, later dismissed
this is unacceptable

2016-11-11 10:18 UTC, zappr-test commented on .zappr.yaml
> +# unreleated change
What are you doing

2016-11-11 10:29 UTC, zappr-test submitted a review, later dismissed
Inacceptable

2016-11-11 10:29 UTC, zappr-test commented on .zappr.yaml
> +
THIS IS WHAT GRINDS MY GEARS

2016-12-05 15:55 UTC, prayerslayer commented
👍

2016-12-05 15:55 UTC, prayerslayer commented
👍

2016-12-05 15:56 UTC, prayerslayer commented
👍

2016-12-06 16:40 UTC, prayerslayer commented
👍

2016-12-06 16:40 UTC, prayerslayer commented
👍

2016-12-06 16:43 UTC, prayerslayer commented
👍

2016-12-21 12:02 UTC, zappr-test submitted a review, later dismissed
I cannot do this for you

2016-12-21 12:02 UTC, zappr-test commented on .zappr.yaml
> +# unreleated change
Can you fix this typo real quick

2016-12-21 12:02 UTC, zappr-test commented on .zappr.yaml
> +
What is this shit

2016-12-21 12:11 UTC, zappr-test requested changes
Maybe you can do better

2016-12-21 12:11 UTC, zappr-test commented on .zappr.yaml
> +# unreleated change
You cant be serious

2016-12-21 12:11 UTC, zappr-test approved these changes

2016-12-21 12:18 UTC, zappr-test requested changes
no

2016-12-21 12:18 UTC, zappr-test commented on .zappr.yaml
> +# unreleated change
starting a review

2016-12-21 14:34 UTC, prayerslayer reviewed
asdf

2016-12-21 14:37 UTC, closed without merging